version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres_container
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
